### ISSUE TITLE
cm-pi-burn fullimage

### ISSUE THREAD

**Issue by Daivik1997** [cloudmesh/cloudmesh_pi_burn#8]
Download: https://downloads.raspberrypi.org/raspbian_full_latest

**Comment by laszewsk** [comment]
Make sure that we can somehow specify the "latest" image on teh command line so we do not have to remember the version. The download will likely rename the file to something that we can do. This shoudl allow us also to detect if we have the latest version downloaded so we do not do this over agin. As far as I remember I implemented this in the past, but it was up to the team to check and make sure it works. As this issue is still open we nee dto verify thsi all again :(

**Comment by rickotten** [comment]
Do we want to specify a name for the img if we have used the "latest" option?
ie. if latest img is '2019-09-26-raspbian-buster-full.img' do we want to rename it to 'latest.img' so we don't need to know the full name of the latest version?

**Comment by laszewsk** [comment]
Is it not doing it by default eg url redirection shouldpoint to the last name

But I am not sure

Also this is a low priority item

laszewski@gmail.com

**Comment by rickotten** [comment]
The URL is fine. The command is fine. 'cm-pi-burn get latest' works (will test later to confirm). The image name is just defined as the name of the original zip file. This is in line with the cm-pi-burn.md documentation though. Low priority so will put this issue on the backburner for now.
